---
name: CI
on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - 'bin/**'
      - 'lib/**'
      - 'spec/**'
      - '*.gemspec'
      - 'Rakefile'
      - 'Gemfile'
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7']
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install latest bundler
        run: |
          gem install bundler --no-document
          bundle config set without 'tools benchmarks docs'
      - name: Install dependencies
        run: bin/setup
      - name: Run tests
        run: bundle exec rake
